using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AUTistima.Migrations
{
    /// <inheritdoc />
    public partial class SeedSchoolsFromSQLFile : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DELETE FROM [autistima_sa_sql].[Schools];
                DBCC CHECKIDENT ('[autistima_sa_sql].[Schools]', RESEED, 0);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTOR HENRIQUE EQUELMAN', N'RUA 56 COHAB -  - JACINTINHO - Maceió', N'Jacintinho', N'57041620', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA DE ENSINO FUNDAMENTAL SAGRADO CORAÇÃO DE JESUS', N'RUA DELMIRO GOUVEIA - SN - CRUZ DAS ALMAS - Maceió', N'Cruz das Almas', N'57038260', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6647625, -35.708704);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL ZANELI CALDAS', N'PRAÇA DA MARAVILHA - 87 - POÇO - Maceió', N'Poço', N'57025860', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6586248, -35.717677);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTOR ORLANDO ARAÚJO', N'RUA DR. JOSÉ SAMPAIO LUZ -  - PONTA VERDE - Maceió', N'Ponta Verde', N'57035260', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6586543, -35.7108819);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL ANTÔNIO SEMEÃO LAMENHA LINS ', N'RUA MAJOR JOSÉ JOAQUIM CALHEIROS -  - JACINTINHO - Maceió', N'Jacintinho', N'57041580', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL ARNON AFONSO FARIAS DE MELO ', N'CONJ. JOSÉ DA SILVA PEIXOTO  -  - JACINTINHO - Maceió', N'Jacintinho', N'57041132', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL CLETO MARQUES LUZ', N'RUA LUIS ALVES DA SILVA - S/N - SANTA AMELIA  - Maceió', N'', N'57063650', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOM ANTÔNIO BRANDÃO ', N'R. DO QUADRO  - SN - TABULEIRO - Maceió', N'Tabuleiro do Martins', N'57061120', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.57362400002035, -35.7636198712411);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTOR POMPEU SARMENTO', N'AVENIDA MUNIZ FALCÃO -  - BARRO DURO - Maceió', N'Clima Bom', N'57071130', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.58332718157225, -35.7396590577506);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI GRACILIANO RAMOS', N'AV.DR. JOSÉ HAILTON DOS SANTOS - S/N - CIDADE UNIVERSITARIA - Maceió', N'Cidade Universitária', N'57073020', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI JOÃO XXIII', N'RUA DR JOSE JOAQUIM ARAÚJO - 57 - JACINTINHO - Maceió', N'Jacintinho', N'57040090', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTOR JOSÉ HAROLDO DA COSTA', N'RUA DR. JÚLIO CÉSAR MENDONÇA UCHÔA -  - TABULEIRO DO MARTINS - Maceió', N'Tabuleiro do Martins', N'57081395', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5685551869336, -35.7569707024559);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSOR LENILTO ALVES SANTOS', N'RUA ENFERMEIRO MARIANO -  - JACINTINHO - Maceió', N'Jacintinho', N'57041430', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL LUÍZA  OLIVEIRA SURUAGY ', N'RUA PADRE CÍCERO -  - OURO PRETO - Maceió', N'Ouro Preto', N'57045815', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56843676193485, -35.7474719326071);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI LUIZ CALHEIROS JÚNIOR', N'RUA LOURIVAL DE AGUIAR PESSOA - 400 - SERRARIA - Maceió', N'Serraria', N'57046770', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5945808, -35.7280492);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MAJOR BONIFÁCIO SILVEIRA', N'AV JORNALISTA JOSÉ BATISTA - 277 - GRUTA DE LOURDES - Maceió', N'Gruta de Lourdes', N'57052645', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6125541, -35.7380054);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MARECHAL FLORIANO PEIXOTO', N'R. DA IGREJA -  - IPIOCA - Maceió', N'Ipioca', N'57039800', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.54659151427341, -35.626679153327);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PADRE PINHO', N'RUA QUEBRANGULO - SN - CRUZ DAS ALMAS - Maceió', N'Cruz das Almas', N'57038460', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6647625, -35.708704);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PEDRO CAFÉ', N'Praça leonidio Cardoso -  - RIO NOVO - Maceió', N'Rio Novo', N'57070570', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.59813271385177, -35.7716783890176);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PEDRO SURUAGY', N'AV. MACEIÓ -  - TABULEIRO - Maceió', N'Tabuleiro do Martins', N'57061110', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56831453902831, -35.7574474398445);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL ALMEIDA LEITE ', N'R. VIRGÍLIO GUEDES - S/N - PONTA GROSSA - Maceió', N'', N'57014002', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSOR DONIZETTE CALHEIROS ', N'RUA JOSE HERMES DAMASCENO - S/N - SANTA LUCIA - Maceió', N'Santa Lúcia', N'57082010', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5865536, -35.7586476);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA EULINA RIBEIRO ALENCAR', N'R. COARACY FONSECA -  - JACINTINHO - Maceió', N'Jacintinho', N'57040080', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL SUZEL DANTAS', N'RUA ANTONIO MONTEIRO DE CARVALHO -  - TABULEIRO DO MARTINS - Maceió', N'Tabuleiro do Martins', N'57060020', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.57132539272584, -35.7567229102561);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL RUI PALMEIRA', N'AV. MONTE CASTELO - SN - VERGEL DO LAGO - Maceió', N'Vergel do Lago', N'57015130', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.66782895040456, -35.7468942394374);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL SÉRGIO LUIZ PESSOA BRAGA', N'AV. GOVERNADOR LAMENHA FILHO -  - CHÃ DA JAQUEIRA - Maceió', N'Chã da Jaqueira', N'57018550', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6191507, -35.7463003);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL SILVESTRE PÉRICLES', N'PRAÇA DR. CAIO PORTO -  - PONTAL DA BARRA - Maceió', N'Pontal da Barra', N'57010830', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68905306290598, -35.7381565498812);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL JAIME DE ALTAVILLA ', N'Rua Dilermando Reis -  - Santa Lúcia - Maceió', N'Santa Lúcia', N'57082045', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5865536, -35.7586476);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSOR CORINTHO DA PAZ', N'CONJ. CIDADE UNIVERSITÁRIA -  - CIDADE UNIVERSITÁRIA - Maceió', N'Cidade Universitária', N'57072014', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSOR ANTÍDIO VIEIRA', N'R. PAULO NETO  - SN - TRAPICHE - Maceió', N'Trapiche da Barra', N'57010380', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68545252498964, -35.7448549331619);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL HIGINO BELO ', N'AV. SANTA RITA DE CÁSSIA  -  - FAROL - Maceió', N'Farol', N'57051600', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6555093, -35.7336269);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI NOSSA SENHORA DA GUIA', N'AV. SIQUEIRA CAMPOS - 24/27 - TRAPICHE - Maceió', N'Trapiche da Barra', N'57010645', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68892362672242, -35.7481439418075);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTOR JOSÉ BANDEIRA DE MEDEIROS', N'GUAICURUS - 77 - PONTA GROSSA - Maceió', N'', N'57014080', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSOR DERALDO CAMPOS', N'PÇ. MOISES S. FIRMINO -  - VERGEL DO LAGO - Maceió', N'Vergel do Lago', N'57015050', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.66792821447216, -35.7516651215879);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA DE LOURDES VIEIRA ', N'PRAÇA GONÇALVES LEDO - s/n - FAROL - Maceió', N'Centro', N'57020050', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6647296, -35.7385312);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI MARECHAL JOÃO BATISTA MASCARENHAS DE MORAES ', N'PRAÇA DR. OSÓRIO CALHEIROS GATTO - S/N - PITANGUINHA - Maceió', N'Pitanguinha', N'57052320', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.64815558700123, -35.7249056351096);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI MONSENHOR LUIS BARBOSA ', N'RUA DIVALDO SURUAGY - 98 - VILLAGE CAMPESTRE II - Maceió', N'Cidade Universitária', N'57073595', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI DOUTOR ANTÔNIO MÁRIO MAFRA ', N'RUA 15 DE MARÇO  - S /N - LEVADA - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68324801296178, -35.7348842416203);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DE ENSINO FUNDAMENTAL SANTO ANTONIO', N'AV. CACHOEIRA DO MEIRIM /LIRA  -  - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57084304', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTOR BALTAZAR DE MENDONÇA ', N'TEN. CEL. EXERC. BRAS. PEDRO JERONIMO DOS SANTOS - S/N - JACINTINHO - Maceió', N'Jacintinho', N'57040780', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL JOSÉ CORREIA COSTA', N'AV EMPRESARIO VALENTIM DOS SANTOS DINIZ - s/n - SERRARIA - Maceió', N'Serraria', N'57046770', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5945808, -35.7280492);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTOR JOSÉ CARNEIRO ', N'RUA BERNADES LOPES - SN - Pinheiro - Maceió', N'Pinheiro', N'57057030', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6276873, -35.7384062);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL KÁTIA PIMENTEL ASSUNÇÃO ', N'RUA BRENO CANSANÇAO - 788 - JACINTINHO - Maceió', N'Jacintinho', N'57041300', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MANOEL PEDRO DOS SANTOS', N'AV. CORINTHO CAMPELO DA PAZ -  - SANTOS DUMONT - Maceió', N'Clima Bom', N'57071230', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.57988003593628, -35.7407534811977);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI WALTER PITOMBO LARANJEIRAS', N'AV GOVERNADOR TEOBALDO BARBOSA - 434 - VERGEL DO LAGO - Maceió', N'Vergel do Lago', N'57015852', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.66860487301587, -35.7516751257093);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSOR MANOEL COELHO NETO ', N'RUA MANOEL FLORENTINO DA SILVA - 190 - PINHEIRO - Maceió', N'Pinheiro', N'57057380', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6276873, -35.7384062);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL TEREZA DE JESUS', N'RUA SARGENTO JAYME PANTALEÃO - 75 - PRADO - Maceió', N'Prado', N'57010200', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68347570688572, -35.7375529017152);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL HERMÍNIO CARDOSO', N'R. BARÃO DE JARAGUÁ - SN - FERNÃO VELHO - Maceió', N'Rio Novo', N'57070540', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.59236622216535, -35.7722544631193);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA JAREDE VIANA DE OLIVEIRA', N'R. SÃO JOSÉ  - 888A - CLIMA BOM - Maceió', N'Clima Bom', N'57071051', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.57904535898876, -35.7398666194959);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA IVONE SANTOS DE OLIVEIRA ', N'CONJ. CIDADE SORRISO I - S/N - BENEDITO BENTES II - Maceió', N'Benedito Bentes', N'57086131', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI GOVERNADOR LUIS ABILIO DE SOUSA NETO ', N'RUA P, CONJ CIDADE SORRISO QD E - SN - BENEDITO BENTES II - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68251005449854, -35.7314684278412);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA APARECIDA BEZERRA NUNES', N'CONJ. RES. DOS PESCADORES RUA ARY PITOMBO - s n - TRAPICHE DA BARRA - Maceió', N'Trapiche da Barra', N'57010386', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68537541686846, -35.7437112752662);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL GASTONE LÚCIA DE CARVALHO BELTRÃO', N'CONJ. RES. JARDIM ROYAL II NÚMERO DO INEP 27051684 - SN - CIDADE UNIVERSITÁRIA - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.67704557311937, -35.7318550477701);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA SÔNIA MARIA SOUZA CAVALCANTI', N'RUA GENERAL  HERMES - S/N - BOM PARTO - Maceió', N'', N'57017201', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI JOSÉ MADLTTON VITOR DA SILVA', N'Loteamento Bela Vista II - s/n - Benedito Bentes - Maceió', N'Benedito Bentes', N'57085540', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA FÚLVIA MARIA DE BARROS MOTT ROSEMBERG', N'Avenida Alice Karoline -  - Cidade Universitária - Maceió', N'Cidade Universitária', N'57073415', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI ANA CAROLINA GALINA FORTES FERREIRA SANTIAGO', N'Conjunto Novo Jardim  - S/N - Cidade Universitária - Maceió', N'Cidade Universitária', N'57072362', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA SALETE DA SILVA', N'AVENIDA ANTÔNIO LISBOA DE AMORIM - S/N - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57085160', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL JOÃO FEITOSA', N'Rua da Areia -  - Rio novo - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6765943717195, -35.7332280898501);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA JOSÉ DE OLIVEIRA ', N'AVENIDA TANCREDO NEVES - SN - BENEDITO BENTES  - Maceió', N'Cidade Universitária', N'57073383', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI MESTRA VIRGÍNIA MORAES DA SILVA', N'RUA SÃO LUIZ, CONJ. VALE DO TOCANTINS -  - RIO NOVO - Maceió', N'Rio Novo', N'57070630', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.59582303089602, -35.7726717319441);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSOR SILVÂNIO BARBOSA DOS SANTOS', N'CONJ RESIDENCIAL JOSÉ APRIGIO VILELA - s/n - JACARECICA - Maceió', N'Jacarecica', N'57032070', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.62121532659095, -35.6994860589119);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA DULCINETE BARROS ALVES', N'LOTEAMENTO CASA FORTE - S/N - ANTARES - Maceió', N'Antares', N'57048166', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.54722220350484, -35.7121137160267);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI MARTHA CÉLIA DE VASCONCELLOS BERNARDES', N'RUA DR. JURACY PEREIRA - S/N - CIDADE UNIVERSITÁRIA - Maceió', N'Cidade Universitária', N'57072040', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA MARIA DE LOURDES BEZERRA NUNES', N'RUA DR WALDEMIRO DE ALENCAR JR - 100 - MANGABEIRAS - Maceió', N'Mangabeiras', N'57037574', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6478561, -35.7147108);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSOR EDVALDO ALBUQUERQUE DOS SANTOS', N'RUA D  - S/N - CIDADE UNIVERSITARIA - Maceió', N'Cidade Universitária', N'57073633', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI JOSE ORLANDO CAJE', N'Avenida B - S/N - CIDADE UNIVERSITARIA - Maceió', N'Cidade Universitária', N'57072170', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA MARIA DA GRACAS SILVA', N'Avenida Dr André Papini de Gois - 177 - Cidade Universitária - Maceió', N'Cidade Universitária', N'57073130', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA ALBENE CLARINDO DUARTE ', N'RUA DR FRANCISCO AGUIRRE CAMARGO - S/N - BARRO DURO - Maceió', N'Barro Duro', N'57045450', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.65018809363235, -35.7435216350656);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA ELISABETE DOS SANTOS VASCONCELOS ', N'Av. Lourival Melo Mota - S/N - SANTOS DUMONT - Maceió', N'Santos Dumont', N'57075970', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5320076, -35.795684);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA SIMONE FERREIRA SIMÃO ', N'Avenida Maceió - 863 - TABULEIRO DO MARTINS - Maceió', N'Tabuleiro do Martins', N'57061110', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.57157438499642, -35.7591512682408);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA ANNE CLEIDE PIMENTEL BEZERRA ', N'Avenida Menino Marcelo - 247 - ANTARES - Maceió', N'Antares', N'57083410', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.55366498233322, -35.7093820021919);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA ZAIRA NASCIMENTO DE OLIVEIRA - 27055680 INEP ', N'Travessa Jatobá - 37 - Chã da Jaqueira - Maceió', N'Chã da Jaqueira', N'57018534', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6191507, -35.7463003);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA IVANEIDE MARIA SANTANA FARIAS ', N'Conjunto Cidade Sorriso 1 - S/N - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57086037', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA NADIR BRANDÃO CAVALCANTE ', N'RUA DA IGREJA - SN - IPIOCA - Maceió', N'Ipioca', N'57039800', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5525095118403, -35.6285154292651);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA CLEIDE GOMES CORDEIRO DA SILVA ', N'RUA ANGELO MARTINS - 270 - PONTA DA TERRA - Maceió', N'', N'57030592', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI ESTUDANTE JOAO PEDRO DA SILVA BERNARDINO ', N'Rua Boa Vista - S/N - OURO PRETO - Maceió', N'Ouro Preto', N'57045811', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.57104080676541, -35.7451496927926);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI DESEMBARGADOR JOSE FERNANDO DE LIMA SOUZA ', N'RUA BARÃO DE ATALAIA - 823 - CENTRO - Maceió', N'Centro', N'57020510', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6647296, -35.7385312);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA LUCINEIDE GOMES FLOR', N'RUA FAUSTINO DA SILVEIRA - 68 - BEBEDOURO - Maceió', N'Bebedouro', N'57017692', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6232608, -35.7516398);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA CLAUDIA MARIA DA SILVA BRASIL', N'AV EMPRESÁRIO NELSON OLIVEIRA MENEZES - 1323 - CIDADE UNIVERSITARIA - Maceió', N'Cidade Universitária', N'57073000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PADRE SILVESTRE VREDEGOOR', N'PARQUE AFRÂNIO JORGE - S/N - PRADO - Maceió', N'Prado', N'57010020', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6823321378845, -35.7375926223515);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL LINDOLFO COLLOR ', N'AV. GOV. THEOBALDO BARBOSA - S/N - VERGEL DO LAGO - Maceió', N'', N'57014510', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOM MIGUEL FENELLON CÂMARA', N'CONJ. JARDIM PETRÓPOLIS II - SN - PETRÓPOLIS - Maceió', N'Petrópolis', N'57062417', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56526147296053, -35.7192611198076);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL ZUMBI DOS PALMARES', N'CONJ. ROSANE COLLOR QD M - SN - CLIMA BOM - Maceió', N'Clima Bom', N'57071470', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.58177105810685, -35.7375960983266);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MARIA CARMELITA CARDOSO GAMA ', N'CAMPUS A.C. SIMÕES -  - CIDADE UNIVERSITÁRIA - Maceió', N'Cidade Universitária', N'57072900', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5552291, -35.7781208);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA NEIDE DE FREITAS FRANÇA', N'POVOADO SAÚDE - IPIOCA - 303 - IPIOCA - Maceió', N'Ipioca', N'57039703', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.54774201029977, -35.630462718136);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL TRADUTOR JOÃO SAMPAIO', N'RUA PERIMETRAL 5 - S/N - CONJ. JOÃO SAMPAIO I - Maceió', N'Petrópolis', N'57062636', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56240286716157, -35.7170995366023);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA DE ENSINO FUNDAMENTAL NOSSA SENHORA APARECIDA', N'RUA PROFESSORA MARIA JOSÉ LOUREIRO LIMA - 200 - PRADO - Maceió', N'Prado', N'57010324', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.67897980407205, -35.7341752064409);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA DE ENSINO FUNDAMENTAL LUIZ PEDRO DA SILVA I ', N'RUA DEPUTADO JOSÉ BERNARDES - 10 - PETRÓPOLIS - Maceió', N'Petrópolis', N'57062195', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56780593897751, -35.7237040532976);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA HÉVIA VALÉRIA MAIA AMORIM', N'CONJ. VILLAGE CAMPESTRE I -  - TABULEIRO - Maceió', N'Cidade Universitária', N'57073490', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA DE ENSINO FUNDAMENTAL NOSSO LAR I', N'RUA PROFESSOR MARIO BROAD - 36 - LEVADA - Maceió', N'', N'57014830', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI BRENO AGRA ', N'AV. ARTHUR VALENTE JUCÁ -  - BENEDITO BENTES I - Maceió', N'Benedito Bentes', N'57084048', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI LEDA COLLOR DE MELLO ', N'RUA EM PROJETO, CONJ. OSMAN LOUREIRO - s/n - TABULEIRO DO MARTINS - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68180775542992, -35.7314916418578);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CRECHE LINDOLFO COLLOR', N'AVENIDA THEOBALDO BARBOSA - S/N - Vergel do Lago - Maceió', N'', N'57014618', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI BENEVIDES EPAMINONDAS DA SILVA', N'AVENIDA GENERAL DE FRANÇA - 1585   - RIACHO DOCE - Maceió', N'Riacho Doce', N'57039230', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5818942343826, -35.648209337093);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CRECHE ROSANE COLLOR', N'RUA JOSE REIS CAMPOS - s/n - JACINTINHO - Maceió', N'Jacintinho', N'57041540', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI MARIA LIEGE TAVARES DE ALBUQUERQUE', N'RUA SÃO JOSÉ - SN - JACINTINHO - Maceió', N'Jacintinho', N'57040510', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6365709, -35.7110774);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI TEREZA DE LISIEUX', N'RUA CÍCERO TORRES - S/N - LEVADA - Maceió', N'Levada', N'57017140', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.67517454245763, -35.7400560480257);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CRECHE SUZANA PALMEIRA', N'RUA ALVARO MARINHO - 855/2 - PRADO - Maceió', N'Prado', N'57010050', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6792718577233, -35.7372654201523);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI HERMÉ MIRANDA  ', N'R. PEDROSA - 203 - TABULEIRO - Maceió', N'Tabuleiro do Martins', N'57081510', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5683657871304, -35.7562344588648);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI AGENOR FERNANDES PONTES ', N'VILA GOIABEIRA - 132 - FERNÃO VELHO - Maceió', N'Fernão Velho', N'57070440', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.60386220532486, -35.7820709277773);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DRA ELIZABETH ANNE LYRA LOPES DE FARIAS', N'R. ROBERT LYRA - 04 - BENEDITO BENTES - Maceió', N'Vergel do Lago', N'57015320', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.67346743474962, -35.7538300209766);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI JOSÉ MARIA DE MELO ', N' RUA BELO HORIZONTE - SN - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57084780', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI VICE-GOVERNADOR FRANCISCO MELLO', N'CONJ. VIRGEM DOS POBRES - S/N - VERGEL DO LAGO - Maceió', N'Trapiche da Barra', N'57010480', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68700456795329, -35.7471657410068);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOM HELDER CÂMARA', N'RUA ACRE - S/N - FEITOSA - Maceió', N'Feitosa', N'57043230', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6306916, -35.7256452);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL SELMA BANDEIRA', N'CONJ SELMA BANDEIRA -  - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57086236', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTORA NISE DA SILVEIRA', N'LOTEAMENTO TERRA DE ANTARES I - SN - SERRARIA - Maceió', N'Antares', N'57048140', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.54823278541899, -35.7094791621512);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL CÍCERA LUCIMAR DE SENA SANTOS', N'Rua José Maria de Lima, antiga 26 de abril - 222 - Poço - Maceió', N'Poço', N'57025570', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6586248, -35.717677);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA ELMA MARQUES CURTI', N'AV. BENEDITO BENTES -  - BENEDITO BENTES II - Maceió', N'Benedito Bentes', N'57084649', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA NILDA DOS SANTOS SILVA', N'RUA SÃO FRANCISCO DE ASSIS -  - CHÃ DA JAQUEIRA - Maceió', N'Chã da Jaqueira', N'57018445', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.616444, -35.7459655);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA RUTH BRAGA QUINTELA CAVALCANTE', N'RUA PASTOR EURICO CALHEIROS - 502 - JACINTINHO - Maceió', N'Jacintinho', N'57041620', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6384785, -35.7124853);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSOR PAULO FREIRE', N'AV. JOSÉ AIRTON GONDIM LAMENHA -  -  SÃO JORGE - Maceió', N'', N'57044098', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSOR PETRÔNIO VIANA', N'CONJUNTO CARMINHA -  - BENEDITO BENTES - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.67895638898082, -35.7384799754209);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSOR AURÉLIO BUARQUE DE HOLANDA FERREIRA ', N'CONJ. FREITAS NETO - S/N - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57086412', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA DE ENSINO FUNDAMENTAL LUIZ PEDRO DA SILVA II ', N'RUA NADJA ABYS FRANÇA - 32 - CLIMA BOM - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68302957795266, -35.7367306974047);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA DE ENSINO FUNDAMENTAL LUIZ PEDRO DA SILVA IV', N'COMPLEXO RESIDENCIAL GAMA LINS -  - CIDADE UNIVERSITÁRIA - Maceió', N'Santa Lúcia', N'57082000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5865536, -35.7586476);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA GERUZA COSTA LIMA', N'RUA SANTA MARGARIDA - 222 - JACINTINHO - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68111673153711, -35.7347595358972);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL FREI DAMIÃO', N'AV MUNDAÚ - 120 - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57085778', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL DOUTOR DENISSON LUIZ CERQUEIRA MENEZES', N'CONJ. DENISSON MENEZES -  - TABULEIRO - Maceió', N'Cidade Universitária', N'57073639', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA MARIA JOSÉ CARRASCOSA ', N'RUA DIEGUES JUNIOR - 224 - POÇO - Maceió', N'Poço', N'57025650', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6586248, -35.717677);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI MESTRE MÁRIO IZALDINO', N'AV SENADOR ARNON DE MELLO - 25 - PONTAL DA BARRA - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68172969643873, -35.738029356439);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA KYRA MARIA BARROS PAES ', N'RUA MUNIZ FALCÃO -  - CLIMA BOM - Maceió', N'Clima Bom', N'57071130', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.57691549313523, -35.741253467185);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PAULO HENRIQUE COSTA BANDEIRA', N'RUA NORMA PIMENTEL DA COSTA - 11 - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57084650', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA NATALINA COSTA CAVALCANTE', N'RUA ROTARY -  - TABULEIRO DO MARTINS - Maceió', N'Tabuleiro do Martins', N'57081132', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56869944977204, -35.7598450289292);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI SÃO SEBASTIÃO', N'RUA EDGAR DE GOES MONTEIRO  - 817 - PRADO - Maceió', N'Prado', N'57010140', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68198684118247, -35.7383476048007);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MARIA DE FÁTIMA LYRA ', N'BENEDITO BENTES I RUA A VINTE E CINCO - 310 - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57084025', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MARIA DE LOURDES DE MELO PIMENTEL', N'RUA PADRE CÍCERO - 05 - CIDADE UNIVERSITARIA - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68106434780435, -35.737972946011);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL OCTÁVIO BRANDÃO', N'RUA JOSE LOBO DE MEDEIROS -  - TABULEIRO - Maceió', N'Tabuleiro do Martins', N'57061100', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56848951767931, -35.7630101689275);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI CASA DA AMIZADE ', N'AV. VEREADOR DARIO MARSIGLIA - 300 - TABULEIRO - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.67880392213741, -35.7377867045641);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PADRE BRANDÃO LIMA ', N'AVENIDA CACHOEIRA DO MEIRIM - S/N - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57084700', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PIO X', N'RUA PROFESSORA MARIA JOSÉ LOUREIRO LIMA - 200 - PRADO - Maceió', N'Prado', N'57010324', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68208206861178, -35.7334387759458);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA SILVIA CELINA NUNES LIMA', N'RUA BENEDITO CALAÇA LOUREIRO - 2001 - CIDADE UNIVERSITÁRIA - Maceió', N'Cidade Universitária', N'57073510', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MARCOS SORIANO', N'CONJ. JARDIM PETROPÓLIS II B -  - PETRÓPOLIS - Maceió', N'Petrópolis', N'57062572', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56889808179245, -35.7176014453428);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL BENEDITA DA SILVA SANTOS ', N'AV ARTHUR VALENTE JUCA - 557 - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57084610', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL CESAR AUGUSTO DE OLIVEIRA', N'R. BOA ESPERANÇA -  - SANTOS DUMONT - Maceió', N'Santos Dumont', N'57075570', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5320076, -35.795684);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL JAIME AMORIM MIRANDA ', N'AV BELMIRO AMORIM  - 760 - TABULEIRO - Maceió', N'Santa Lúcia', N'57082000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5865536, -35.7586476);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL OLAVO BILAC', N'RUA GOVERNADOR LAMENHA FILHO - SN - FEITOSA - Maceió', N'Feitosa', N'57043000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6306916, -35.7256452);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL YEDA OLIVEIRA DOS SANTOS', N'AV JOSÉ CAMELO DE FREITAS - 595 - CIDADE UNIVERSITARIA - Maceió', N'Cidade Universitária', N'57073360', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI HELOÍSA MARINHO DE GUSMÃO MEDEIROS ', N'AVENIDA MOACIR ANDRADE -  - BENEDITO BENTES II - Maceió', N'Benedito Bentes', N'57086171', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA MARILUCIA MACEDO DOS SANTOS', N'RUA ANTÔNIO ZEFERINO DOS SANTOS - 20 - JACINTINHO - Maceió', N'Jacintinho', N'57042030', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6384785, -35.7124853);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA DE FÁTIMA MELO DOS SANTOS ', N'AVENIDA MACEIO       - 342 - TABULEIRO - Maceió', N'Tabuleiro do Martins', N'57061110', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.57167852130199, -35.7601891326778);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MONSENHOR ANTÔNIO ASSUNÇÃO ARAÚJO', N'RUA ARACI MARTINS DA SILVA - 04 - SERRARIA - Maceió', N'Serraria', N'57046161', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5945808, -35.7280492);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA MARIZETTE CORREIA NUNES BRUNO', N'AVENIDA MENINO MARCELO LOTEAMENTO CASA FORTE  - 08 - SERRARIA - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.67841169043449, -35.7317200444119);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA ZILKA DE OLIVEIRA GRAÇA', N'RUA JOSÉ GONZAGA DE ALMEIDA - 276 - TABULEIRO DO MARTINS - Maceió', N'Tabuleiro do Martins', N'57061060', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56707308219645, -35.7594023343747);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA MARIA DO SOCORRO TAVARES LIMA DA SILVA', N'RUA CARLOS DE MIRANDA - 257 - POÇO - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68233059517171, -35.7330946156743);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL CÍCERO DUÉ DA SILVA', N'AV. MENINO MARCELO - 1391 - CIDADE UNIVERTÁRIA - Maceió', N'Cidade Universitária', N'57073460', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5539008, -35.7461255);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI JORGE DE LIMA ', N'AV. BELMIRO AMORIM - 1750 - SANTA LÚCIA - Maceió', N'Santa Lúcia', N'57082000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5865536, -35.7586476);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA MARIA JOSÉ CLEMENTE ROCHA', N'RUA A 5 - 47 - BENEDITO BENTES  - Maceió', N'Poço', N'57025673', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6586248, -35.717677);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PROFESSORA CLAUDINETE BATISTA DA SILVA', N'R. ARY PITOMBO - 290 - TRAPICHE - Maceió', N'Trapiche da Barra', N'57010376', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6880427971936, -35.7459263779812);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI TOBIAS GRANJA', N'AV. JORN. TEOFILO A. LINS -  - CLIMA BOM - Maceió', N'Clima Bom', N'57071820', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.58382324823213, -35.7360674005005);
            ");
            migrationBuilder.Sql(@"
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI HERBERT DE SOUZA  ', N'AV. GAL LUIZ DE FRANÇA ALBUQUERQUE - s/n - JACARECICA - Maceió', N'Prado', N'57010000', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.68112661072629, -35.7314143293695);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI VEREADOR BRAGA NETO', N'RUA ELIETE ROLEMBERG DE FIGUEIREDO - 163 - TABULEIRO DOS MARTINS - Maceió', N'Tabuleiro do Martins', N'57061070', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56612851242515, -35.7637679909151);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL PEDRO BARBOSA JÚNIOR', N'RUA ARNALDO BRAGA  -  - CRUZ DAS ALMAS - Maceió', N'Cruz das Almas', N'57038130', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.6647625, -35.708704);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSORA ELZA LIRA', N'CONJ SELMA BANDEIRA -  - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57086281', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL MARIA CECILIA PONTES CARNAÚBA', N'AV. GILBERTO SOARES PINTO - 763 - ANTARES I - Maceió', N'Antares', N'57048260', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.55004915985304, -35.7121244137866);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL AUDIVAL AMÉLIO DA SILVA ', N'RUA ANA PAULA - SN - SÃO JORGE - Maceió', N'', N'57044132', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'ESCOLA MUNICIPAL RADIALISTA EDÉCIO LOPES', N'ALAMEDA CELIA DOS ANJOS -  Nº 06 - PETROPOLIS - Maceió', N'Petrópolis', N'57062200', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.56879731405515, -35.7238417636864);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PROFESSOR RANILSON FRANÇA DE SOUZA', N'RUA PROF. MARIO BROAD - 36 - LEVADA - Maceió', N'', N'57014530', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), NULL, NULL);
                INSERT INTO [autistima_sa_sql].[Schools] ([Nome], [Endereco], [Bairro], [CEP], [Cidade], [Estado], [EscolaPublica], [PossuiSalaRecursos], [Ativo], [DataCadastro], [Latitude], [Longitude]) VALUES (N'CMEI PRESIDENTE FRANCISCO DE PAULA RODRIGUES ALVES', N'AV. CACHOEIRA DO MEIRIM -  - BENEDITO BENTES - Maceió', N'Benedito Bentes', N'57084700', N'Maceió', N'AL', 1, 0, 1, GETUTCDATE(), -9.5859671, -35.7150116);
            ");

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM [autistima_sa_sql].[Schools]");
        }
    }
}
